### ISSUE TITLE
Question about using foo.ng on CF

### ISSUE THREAD

**Issue by SevenworksDev** [Pokymon/foo.ng#17]
I was scrolling through a list of free subdomain providers on github thats super small so I don't have a long link. I'm not a domain nerd and I don't really see the option to add a subdomain from another domain thats not on my cloudflare account so i can use it on one of my sites. Would you know if using a foo.ng subdomain is possible on a cloudflare tunnel?

**Comment by Pokymon** [comment]
I'm not familiar with Cloudflare Tunnel but I asked ChatGPT and it said, "Yes, you can use Cloudflare Tunnel with domains that are not managed by Cloudflare DNS".
