### ISSUE TITLE
Can I use sub-subdomains here?

### ISSUE THREAD

**Issue by ServerDeveloper9447** [Pokymon/foo.ng#22]
I need a subdomain for my guilded bot but the main website and the dashboard are on different servers.
I would be helpful if all servers come under the same subdomain
like `project.foo.ng` and `dashboard.project.foo.ng`

is it possible?

**Comment by Pokymon** [comment]
Yes, it's possible. You can just write "dashboard.project" for that one.

**Comment by ServerDeveloper9447** [comment]
> Yes, it's possible. You can just write "dashboard.project" for that one.

Thanks
