### ISSUE TITLE
Vercel Domain Help

### ISSUE THREAD

**Issue by LoganPaxton** [Pokymon/foo.ng#3]
So, I was trying to connect my domain (loganpaxton.foo.ng) to Vercel, my CNAME is set to loganpaxton.vercel.app, but I go to the (domain)[loganpaxton.foo.ng], and it says "Invalid deployment", I go to the domain dashboard (on Vercel), and I try and connect the domain, but this message shows "Another Vercel account is using this domain. Set the following TXT record on _vercel.foo.ng to use loganpaxton.foo.ng in this project. Once the verification is completed and the domain is successfully configured, the TXT record can be removed." How do I fix it?

Screenshot

![Screenshot](https://github.com/Pokymon/foo.ng/assets/111173907/17f14715-0c3e-46d1-afce-76a70aa765d0)

**Comment by Pokymon** [comment]
I have added the TXT record. Could you refresh the verification?

**Comment by LoganPaxton** [comment]
Thanks! It worked!
