### ISSUE TITLE
Vercel Issues With New Domain

### ISSUE THREAD

**Issue by ghost3jelly** [Pokymon/foo.ng#8]
Hello, sorry if this is the wrong place to ask and if needed I will delete this if it is but I am having some issues with my new domain and vercel. I have a website (https://santii.vercel.app/)  and I added the domain here and now I have santii.foo.ng but when running that on a browser I get an error that the vercel deployment was not found. Do I need to go into vercel and change the custom domain itself? If so I get this message bellow.

Again sorry if this is not the right place to send this and thanks for all the great work yall do. Please let me know if it isnt the right place and I will delete the issue.

![Screenshot 2024-06-05 083612](https://github.com/Pokymon/foo.ng/assets/130874019/32f770d4-47cd-4579-89dc-0505e7e18793)

**Comment by Pokymon** [comment]
I have added the TXT record. Could you please refresh it?

**Comment by ghost3jelly** [comment]
Hmm it still shows me the same error. I have refreshed the domain in Vercel and it also says the same message (attached again bellow)
![image](https://github.com/Pokymon/foo.ng/assets/130874019/11bf9e82-2d69-4274-b6dd-7e53b8c906af)

**Comment by Pokymon** [comment]
Could you refresh it again? I mistyped the TXT record.

**Comment by ghost3jelly** [comment]
It works perfectly now, thank you so much for the subdomain and all your help!

**Comment by Pokymon** [comment]
My pleasure! :)
